// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: assignments.sql

package sqlcgen

import (
	"context"
	"time"
)

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO assignments (trip_id, bus_id, driver_id, scheduled_start, scheduled_end, trip_status)
SELECT t.id, $1, $2, t.scheduled_start, t.scheduled_end, t.status
FROM trips t
WHERE t.id = $3
RETURNING id, trip_id, bus_id, driver_id, scheduled_start, scheduled_end, trip_status,
          created_at, updated_at
`

type CreateAssignmentParams struct {
	BusID    int64
	DriverID int64
	TripID   int64
}

// The time window and status are copied straight from the trip row, so the composite FK
// (trip_id, scheduled_start, scheduled_end, trip_status) always matches and the EXCLUDE
// constraints see the real window. The app never supplies those values itself.
func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, createAssignment, arg.BusID, arg.DriverID, arg.TripID)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.BusID,
		&i.DriverID,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.TripStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAssignmentForTrip = `-- name: DeleteAssignmentForTrip :execrows
DELETE FROM assignments WHERE trip_id = $1
`

// Refused by the assignments_lock_completed trigger once the trip is completed:
// payroll must not lose who drove it.
func (q *Queries) DeleteAssignmentForTrip(ctx context.Context, tripID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAssignmentForTrip, tripID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findBusConflicts = `-- name: FindBusConflicts :many
SELECT a.trip_id, a.bus_id, a.driver_id, a.scheduled_start, a.scheduled_end,
       t.origin, t.destination
FROM assignments a
JOIN trips t ON t.id = a.trip_id
WHERE a.bus_id = $1
  AND a.trip_status <> 'cancelled'
  AND a.trip_id <> $2
  AND tstzrange(a.scheduled_start, a.scheduled_end, '[)')
      && tstzrange($3, $4, '[)')
ORDER BY a.scheduled_start
LIMIT 5
`

type FindBusConflictsParams struct {
	BusID         int64
	ExcludeTripID int64
	WindowStart   interface{}
	WindowEnd     interface{}
}

type FindBusConflictsRow struct {
	TripID         int64
	BusID          int64
	DriverID       int64
	ScheduledStart time.Time
	ScheduledEnd   time.Time
	Origin         string
	Destination    string
}

// Service-layer pre-check, purely so the user gets a readable message. The EXCLUDE
// constraint is what actually guarantees the invariant under concurrency.
func (q *Queries) FindBusConflicts(ctx context.Context, arg FindBusConflictsParams) ([]FindBusConflictsRow, error) {
	rows, err := q.db.Query(ctx, findBusConflicts,
		arg.BusID,
		arg.ExcludeTripID,
		arg.WindowStart,
		arg.WindowEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindBusConflictsRow{}
	for rows.Next() {
		var i FindBusConflictsRow
		if err := rows.Scan(
			&i.TripID,
			&i.BusID,
			&i.DriverID,
			&i.ScheduledStart,
			&i.ScheduledEnd,
			&i.Origin,
			&i.Destination,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findDriverConflicts = `-- name: FindDriverConflicts :many
SELECT a.trip_id, a.bus_id, a.driver_id, a.scheduled_start, a.scheduled_end,
       t.origin, t.destination
FROM assignments a
JOIN trips t ON t.id = a.trip_id
WHERE a.driver_id = $1
  AND a.trip_status <> 'cancelled'
  AND a.trip_id <> $2
  AND tstzrange(a.scheduled_start, a.scheduled_end, '[)')
      && tstzrange($3, $4, '[)')
ORDER BY a.scheduled_start
LIMIT 5
`

type FindDriverConflictsParams struct {
	DriverID      int64
	ExcludeTripID int64
	WindowStart   interface{}
	WindowEnd     interface{}
}

type FindDriverConflictsRow struct {
	TripID         int64
	BusID          int64
	DriverID       int64
	ScheduledStart time.Time
	ScheduledEnd   time.Time
	Origin         string
	Destination    string
}

func (q *Queries) FindDriverConflicts(ctx context.Context, arg FindDriverConflictsParams) ([]FindDriverConflictsRow, error) {
	rows, err := q.db.Query(ctx, findDriverConflicts,
		arg.DriverID,
		arg.ExcludeTripID,
		arg.WindowStart,
		arg.WindowEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindDriverConflictsRow{}
	for rows.Next() {
		var i FindDriverConflictsRow
		if err := rows.Scan(
			&i.TripID,
			&i.BusID,
			&i.DriverID,
			&i.ScheduledStart,
			&i.ScheduledEnd,
			&i.Origin,
			&i.Destination,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignmentForTrip = `-- name: GetAssignmentForTrip :one
SELECT id, trip_id, bus_id, driver_id, scheduled_start, scheduled_end, trip_status,
       created_at, updated_at
FROM assignments
WHERE trip_id = $1
`

func (q *Queries) GetAssignmentForTrip(ctx context.Context, tripID int64) (Assignment, error) {
	row := q.db.QueryRow(ctx, getAssignmentForTrip, tripID)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.BusID,
		&i.DriverID,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.TripStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssignmentsInRange = `-- name: ListAssignmentsInRange :many
SELECT a.id, a.trip_id, a.bus_id, a.driver_id, a.scheduled_start, a.scheduled_end,
       a.trip_status, b.plate AS bus_plate, d.full_name AS driver_name,
       t.origin, t.destination
FROM assignments a
JOIN buses b ON b.id = a.bus_id
JOIN drivers d ON d.id = a.driver_id
JOIN trips t ON t.id = a.trip_id
WHERE tstzrange(a.scheduled_start, a.scheduled_end, '[)')
      && tstzrange($1, $2, '[)')
ORDER BY b.plate, a.scheduled_start
`

type ListAssignmentsInRangeParams struct {
	RangeStart interface{}
	RangeEnd   interface{}
}

type ListAssignmentsInRangeRow struct {
	ID             int64
	TripID         int64
	BusID          int64
	DriverID       int64
	ScheduledStart time.Time
	ScheduledEnd   time.Time
	TripStatus     TripStatus
	BusPlate       string
	DriverName     string
	Origin         string
	Destination    string
}

// Feeds the planning list and (step 4) the timeline.
func (q *Queries) ListAssignmentsInRange(ctx context.Context, arg ListAssignmentsInRangeParams) ([]ListAssignmentsInRangeRow, error) {
	rows, err := q.db.Query(ctx, listAssignmentsInRange, arg.RangeStart, arg.RangeEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssignmentsInRangeRow{}
	for rows.Next() {
		var i ListAssignmentsInRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.BusID,
			&i.DriverID,
			&i.ScheduledStart,
			&i.ScheduledEnd,
			&i.TripStatus,
			&i.BusPlate,
			&i.DriverName,
			&i.Origin,
			&i.Destination,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
