// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: audit_log.sql

package sqlcgen

import (
	"context"
	"net/netip"
	"time"
)

const insertAuditEntry = `-- name: InsertAuditEntry :one
INSERT INTO audit_log (actor_user_id, action, entity, entity_id, before, after, ip, request_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, created_at
`

type InsertAuditEntryParams struct {
	ActorUserID *int64
	Action      string
	Entity      string
	EntityID    *int64
	Before      []byte
	After       []byte
	Ip          *netip.Addr
	RequestID   *string
}

type InsertAuditEntryRow struct {
	ID        int64
	CreatedAt time.Time
}

// Written inside the same transaction as the mutation it describes, so a mutation can
// never be committed without its audit row. The app role has INSERT/SELECT only.
func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) (InsertAuditEntryRow, error) {
	row := q.db.QueryRow(ctx, insertAuditEntry,
		arg.ActorUserID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Before,
		arg.After,
		arg.Ip,
		arg.RequestID,
	)
	var i InsertAuditEntryRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listAuditEntriesForEntity = `-- name: ListAuditEntriesForEntity :many
SELECT id, actor_user_id, action, entity, entity_id, before, after, ip, request_id, created_at
FROM audit_log
WHERE entity = $1 AND entity_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListAuditEntriesForEntityParams struct {
	Entity   string
	EntityID *int64
	Limit    int32
}

func (q *Queries) ListAuditEntriesForEntity(ctx context.Context, arg ListAuditEntriesForEntityParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditEntriesForEntity, arg.Entity, arg.EntityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.Entity,
			&i.EntityID,
			&i.Before,
			&i.After,
			&i.Ip,
			&i.RequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
