// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: buses.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBus = `-- name: CreateBus :one
INSERT INTO buses (plate, model, seats, status, insurance_expiry, inspection_expiry)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, plate, model, seats, status, insurance_expiry, inspection_expiry, created_at, updated_at
`

type CreateBusParams struct {
	Plate            string
	Model            string
	Seats            int16
	Status           BusStatus
	InsuranceExpiry  pgtype.Date
	InspectionExpiry pgtype.Date
}

func (q *Queries) CreateBus(ctx context.Context, arg CreateBusParams) (Bus, error) {
	row := q.db.QueryRow(ctx, createBus,
		arg.Plate,
		arg.Model,
		arg.Seats,
		arg.Status,
		arg.InsuranceExpiry,
		arg.InspectionExpiry,
	)
	var i Bus
	err := row.Scan(
		&i.ID,
		&i.Plate,
		&i.Model,
		&i.Seats,
		&i.Status,
		&i.InsuranceExpiry,
		&i.InspectionExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBus = `-- name: DeleteBus :execrows
DELETE FROM buses WHERE id = $1
`

// The FK from assignments is ON DELETE RESTRICT, so a bus that has ever been assigned
// cannot be deleted; retire it instead (status = 'retired').
func (q *Queries) DeleteBus(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBus, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBus = `-- name: GetBus :one
SELECT id, plate, model, seats, status, insurance_expiry, inspection_expiry, created_at, updated_at
FROM buses
WHERE id = $1
`

func (q *Queries) GetBus(ctx context.Context, id int64) (Bus, error) {
	row := q.db.QueryRow(ctx, getBus, id)
	var i Bus
	err := row.Scan(
		&i.ID,
		&i.Plate,
		&i.Model,
		&i.Seats,
		&i.Status,
		&i.InsuranceExpiry,
		&i.InspectionExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveBuses = `-- name: ListActiveBuses :many
SELECT id, plate, model, seats, status, insurance_expiry, inspection_expiry, created_at, updated_at
FROM buses
WHERE status = 'active'
ORDER BY plate
`

// Candidates for an assignment: a bus in maintenance or retired is not offered.
func (q *Queries) ListActiveBuses(ctx context.Context) ([]Bus, error) {
	rows, err := q.db.Query(ctx, listActiveBuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bus{}
	for rows.Next() {
		var i Bus
		if err := rows.Scan(
			&i.ID,
			&i.Plate,
			&i.Model,
			&i.Seats,
			&i.Status,
			&i.InsuranceExpiry,
			&i.InspectionExpiry,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuses = `-- name: ListBuses :many
SELECT id, plate, model, seats, status, insurance_expiry, inspection_expiry, created_at, updated_at
FROM buses
ORDER BY plate
`

func (q *Queries) ListBuses(ctx context.Context) ([]Bus, error) {
	rows, err := q.db.Query(ctx, listBuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bus{}
	for rows.Next() {
		var i Bus
		if err := rows.Scan(
			&i.ID,
			&i.Plate,
			&i.Model,
			&i.Seats,
			&i.Status,
			&i.InsuranceExpiry,
			&i.InspectionExpiry,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBus = `-- name: UpdateBus :one
UPDATE buses
SET plate = $2, model = $3, seats = $4, status = $5, insurance_expiry = $6, inspection_expiry = $7
WHERE id = $1
RETURNING id, plate, model, seats, status, insurance_expiry, inspection_expiry, created_at, updated_at
`

type UpdateBusParams struct {
	ID               int64
	Plate            string
	Model            string
	Seats            int16
	Status           BusStatus
	InsuranceExpiry  pgtype.Date
	InspectionExpiry pgtype.Date
}

func (q *Queries) UpdateBus(ctx context.Context, arg UpdateBusParams) (Bus, error) {
	row := q.db.QueryRow(ctx, updateBus,
		arg.ID,
		arg.Plate,
		arg.Model,
		arg.Seats,
		arg.Status,
		arg.InsuranceExpiry,
		arg.InspectionExpiry,
	)
	var i Bus
	err := row.Scan(
		&i.ID,
		&i.Plate,
		&i.Model,
		&i.Seats,
		&i.Status,
		&i.InsuranceExpiry,
		&i.InspectionExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
