// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: drivers.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const anonymizeDriver = `-- name: AnonymizeDriver :one
UPDATE drivers
SET full_name = $2, phone = NULL, license_number = NULL, license_expiry = NULL,
    is_active = false, anonymized_at = now()
WHERE id = $1 AND anonymized_at IS NULL
RETURNING id, full_name, phone, license_number, license_expiry, hourly_rate, pay_type,
          is_active, anonymized_at, created_at, updated_at
`

type AnonymizeDriverParams struct {
	ID       int64
	FullName string
}

// GDPR erasure. The row survives so assignments, worked time and the audit trail keep
// their referential integrity (payroll-seam); only the identifying fields are dropped.
// Idempotent: a second call matches no row and returns no result.
func (q *Queries) AnonymizeDriver(ctx context.Context, arg AnonymizeDriverParams) (Driver, error) {
	row := q.db.QueryRow(ctx, anonymizeDriver, arg.ID, arg.FullName)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.LicenseNumber,
		&i.LicenseExpiry,
		&i.HourlyRate,
		&i.PayType,
		&i.IsActive,
		&i.AnonymizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDriver = `-- name: CreateDriver :one
INSERT INTO drivers (full_name, phone, license_number, license_expiry, hourly_rate, pay_type)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, full_name, phone, license_number, license_expiry, hourly_rate, pay_type,
          is_active, anonymized_at, created_at, updated_at
`

type CreateDriverParams struct {
	FullName      string
	Phone         *string
	LicenseNumber *string
	LicenseExpiry pgtype.Date
	HourlyRate    pgtype.Numeric
	PayType       NullPayType
}

// payroll-seam: hourly_rate and pay_type are accepted and stored but no code reads them
// in the MVP. Payroll later = worked hours (trips.actual_*) x rate, no migration needed.
func (q *Queries) CreateDriver(ctx context.Context, arg CreateDriverParams) (Driver, error) {
	row := q.db.QueryRow(ctx, createDriver,
		arg.FullName,
		arg.Phone,
		arg.LicenseNumber,
		arg.LicenseExpiry,
		arg.HourlyRate,
		arg.PayType,
	)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.LicenseNumber,
		&i.LicenseExpiry,
		&i.HourlyRate,
		&i.PayType,
		&i.IsActive,
		&i.AnonymizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDriver = `-- name: GetDriver :one
SELECT id, full_name, phone, license_number, license_expiry, hourly_rate, pay_type,
       is_active, anonymized_at, created_at, updated_at
FROM drivers
WHERE id = $1
`

func (q *Queries) GetDriver(ctx context.Context, id int64) (Driver, error) {
	row := q.db.QueryRow(ctx, getDriver, id)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.LicenseNumber,
		&i.LicenseExpiry,
		&i.HourlyRate,
		&i.PayType,
		&i.IsActive,
		&i.AnonymizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDriverLoginUserID = `-- name: GetDriverLoginUserID :one
SELECT id FROM users WHERE driver_id = $1
`

// The login account tied to a driver, if any; used to revoke sessions on erasure.
func (q *Queries) GetDriverLoginUserID(ctx context.Context, driverID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, getDriverLoginUserID, driverID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listActiveDrivers = `-- name: ListActiveDrivers :many
SELECT id, full_name, phone, license_number, license_expiry, hourly_rate, pay_type,
       is_active, anonymized_at, created_at, updated_at
FROM drivers
WHERE is_active
ORDER BY full_name
`

// Candidates for an assignment.
func (q *Queries) ListActiveDrivers(ctx context.Context) ([]Driver, error) {
	rows, err := q.db.Query(ctx, listActiveDrivers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Driver{}
	for rows.Next() {
		var i Driver
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Phone,
			&i.LicenseNumber,
			&i.LicenseExpiry,
			&i.HourlyRate,
			&i.PayType,
			&i.IsActive,
			&i.AnonymizedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDrivers = `-- name: ListDrivers :many
SELECT id, full_name, phone, license_number, license_expiry, hourly_rate, pay_type,
       is_active, anonymized_at, created_at, updated_at
FROM drivers
ORDER BY full_name
`

func (q *Queries) ListDrivers(ctx context.Context) ([]Driver, error) {
	rows, err := q.db.Query(ctx, listDrivers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Driver{}
	for rows.Next() {
		var i Driver
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Phone,
			&i.LicenseNumber,
			&i.LicenseExpiry,
			&i.HourlyRate,
			&i.PayType,
			&i.IsActive,
			&i.AnonymizedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDriver = `-- name: UpdateDriver :one
UPDATE drivers
SET full_name = $2, phone = $3, license_number = $4, license_expiry = $5,
    hourly_rate = $6, pay_type = $7, is_active = $8
WHERE id = $1 AND anonymized_at IS NULL
RETURNING id, full_name, phone, license_number, license_expiry, hourly_rate, pay_type,
          is_active, anonymized_at, created_at, updated_at
`

type UpdateDriverParams struct {
	ID            int64
	FullName      string
	Phone         *string
	LicenseNumber *string
	LicenseExpiry pgtype.Date
	HourlyRate    pgtype.Numeric
	PayType       NullPayType
	IsActive      bool
}

func (q *Queries) UpdateDriver(ctx context.Context, arg UpdateDriverParams) (Driver, error) {
	row := q.db.QueryRow(ctx, updateDriver,
		arg.ID,
		arg.FullName,
		arg.Phone,
		arg.LicenseNumber,
		arg.LicenseExpiry,
		arg.HourlyRate,
		arg.PayType,
		arg.IsActive,
	)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.LicenseNumber,
		&i.LicenseExpiry,
		&i.HourlyRate,
		&i.PayType,
		&i.IsActive,
		&i.AnonymizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
