// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type BusStatus string

const (
	BusStatusActive      BusStatus = "active"
	BusStatusMaintenance BusStatus = "maintenance"
	BusStatusRetired     BusStatus = "retired"
)

func (e *BusStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BusStatus(s)
	case string:
		*e = BusStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BusStatus: %T", src)
	}
	return nil
}

type NullBusStatus struct {
	BusStatus BusStatus
	Valid     bool // Valid is true if BusStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBusStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BusStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BusStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBusStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BusStatus), nil
}

type PayType string

const (
	PayTypeHourly  PayType = "hourly"
	PayTypePerTrip PayType = "per_trip"
	PayTypeMonthly PayType = "monthly"
)

func (e *PayType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PayType(s)
	case string:
		*e = PayType(s)
	default:
		return fmt.Errorf("unsupported scan type for PayType: %T", src)
	}
	return nil
}

type NullPayType struct {
	PayType PayType
	Valid   bool // Valid is true if PayType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPayType) Scan(value interface{}) error {
	if value == nil {
		ns.PayType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PayType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPayType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PayType), nil
}

type PaymentStatus string

const (
	PaymentStatusUnpaid      PaymentStatus = "unpaid"
	PaymentStatusReserved    PaymentStatus = "reserved"
	PaymentStatusAdvancePaid PaymentStatus = "advance_paid"
	PaymentStatusPaid        PaymentStatus = "paid"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus
	Valid         bool // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type TripStatus string

const (
	TripStatusPlanned    TripStatus = "planned"
	TripStatusInProgress TripStatus = "in_progress"
	TripStatusCompleted  TripStatus = "completed"
	TripStatusCancelled  TripStatus = "cancelled"
)

func (e *TripStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TripStatus(s)
	case string:
		*e = TripStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TripStatus: %T", src)
	}
	return nil
}

type NullTripStatus struct {
	TripStatus TripStatus
	Valid      bool // Valid is true if TripStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTripStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TripStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TripStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTripStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TripStatus), nil
}

type UserRole string

const (
	UserRoleAdmin      UserRole = "admin"
	UserRoleDispatcher UserRole = "dispatcher"
	UserRoleDriver     UserRole = "driver"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Assignment struct {
	ID             int64
	TripID         int64
	BusID          int64
	DriverID       int64
	ScheduledStart time.Time
	ScheduledEnd   time.Time
	TripStatus     TripStatus
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type AuditLog struct {
	ID          int64
	ActorUserID *int64
	Action      string
	Entity      string
	EntityID    *int64
	Before      []byte
	After       []byte
	Ip          *netip.Addr
	RequestID   *string
	CreatedAt   time.Time
}

type Bus struct {
	ID               int64
	Plate            string
	Model            string
	Seats            int16
	Status           BusStatus
	InsuranceExpiry  pgtype.Date
	InspectionExpiry pgtype.Date
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Driver struct {
	ID            int64
	FullName      string
	Phone         *string
	LicenseNumber *string
	LicenseExpiry pgtype.Date
	HourlyRate    pgtype.Numeric
	PayType       NullPayType
	IsActive      bool
	AnonymizedAt  *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Session struct {
	TokenHash  []byte
	UserID     int64
	CsrfSecret []byte
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
}

type Trip struct {
	ID             int64
	Origin         string
	Destination    string
	ScheduledStart time.Time
	ScheduledEnd   time.Time
	ActualStart    *time.Time
	ActualEnd      *time.Time
	Status         TripStatus
	Notes          *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	PaymentStatus  PaymentStatus
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	Role         UserRole
	DriverID     *int64
	Locale       *string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
