// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: sessions.sql

package sqlcgen

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token_hash, user_id, csrf_secret, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING token_hash, user_id, csrf_secret, created_at, last_seen_at, expires_at
`

type CreateSessionParams struct {
	TokenHash  []byte
	UserID     int64
	CsrfSecret []byte
	ExpiresAt  time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.CsrfSecret,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.CsrfSecret,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= now() OR last_seen_at <= $1
`

// Background purge; $1 = now() - idle timeout.
func (q *Queries) DeleteExpiredSessions(ctx context.Context, lastSeenAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, lastSeenAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :exec
DELETE FROM sessions WHERE user_id = $1
`

// Used on password change, deactivation and "log out everywhere".
func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteSessionsForUser, userID)
	return err
}

const getAndTouchSession = `-- name: GetAndTouchSession :one
UPDATE sessions s
SET last_seen_at = now()
FROM users u
WHERE s.token_hash = $1
  AND u.id = s.user_id
  AND s.expires_at > now()
  AND s.last_seen_at > $2
  AND u.is_active
RETURNING s.token_hash, s.user_id, s.csrf_secret, s.created_at, s.last_seen_at, s.expires_at,
          u.email, u.role, u.driver_id, u.locale
`

type GetAndTouchSessionParams struct {
	TokenHash  []byte
	LastSeenAt time.Time
}

type GetAndTouchSessionRow struct {
	TokenHash  []byte
	UserID     int64
	CsrfSecret []byte
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
	Email      string
	Role       UserRole
	DriverID   *int64
	Locale     *string
}

// Resolves a session and refreshes its idle clock in one round trip. Expiry is enforced
// here, in SQL, not only in Go:
//
//	s.expires_at  > now()  -> absolute expiry
//	s.last_seen_at > $2    -> idle expiry ($2 = now() - idle timeout)
//	u.is_active            -> deactivating a user kills their live sessions immediately
func (q *Queries) GetAndTouchSession(ctx context.Context, arg GetAndTouchSessionParams) (GetAndTouchSessionRow, error) {
	row := q.db.QueryRow(ctx, getAndTouchSession, arg.TokenHash, arg.LastSeenAt)
	var i GetAndTouchSessionRow
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.CsrfSecret,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.Email,
		&i.Role,
		&i.DriverID,
		&i.Locale,
	)
	return i, err
}
