// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: trips.sql

package sqlcgen

import (
	"context"
	"time"
)

const createTrip = `-- name: CreateTrip :one
INSERT INTO trips (origin, destination, scheduled_start, scheduled_end, notes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, origin, destination, scheduled_start, scheduled_end, actual_start, actual_end,
          status, notes, created_at, updated_at
`

type CreateTripParams struct {
	Origin         string
	Destination    string
	ScheduledStart time.Time
	ScheduledEnd   time.Time
	Notes          *string
}

func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, createTrip,
		arg.Origin,
		arg.Destination,
		arg.ScheduledStart,
		arg.ScheduledEnd,
		arg.Notes,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.Origin,
		&i.Destination,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.ActualStart,
		&i.ActualEnd,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTrip = `-- name: DeleteTrip :execrows
DELETE FROM trips WHERE id = $1
`

// Blocked by the assignments FK while the trip is assigned; cancel it instead.
func (q *Queries) DeleteTrip(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTrip, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishTripAsDriver = `-- name: FinishTripAsDriver :one
UPDATE trips
SET status = 'completed', actual_end = now()
FROM assignments a
WHERE trips.id = $1
  AND a.trip_id = trips.id
  AND a.driver_id = $2
  AND trips.status = 'in_progress'
RETURNING trips.id, trips.origin, trips.destination, trips.scheduled_start, trips.scheduled_end,
          trips.actual_start, trips.actual_end, trips.status, trips.notes,
          trips.created_at, trips.updated_at
`

type FinishTripAsDriverParams struct {
	TripID   int64
	DriverID int64
}

// payroll-seam: actual_end closes the worked-time window.
func (q *Queries) FinishTripAsDriver(ctx context.Context, arg FinishTripAsDriverParams) (Trip, error) {
	row := q.db.QueryRow(ctx, finishTripAsDriver, arg.TripID, arg.DriverID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.Origin,
		&i.Destination,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.ActualStart,
		&i.ActualEnd,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrip = `-- name: GetTrip :one
SELECT id, origin, destination, scheduled_start, scheduled_end, actual_start, actual_end,
       status, notes, created_at, updated_at
FROM trips
WHERE id = $1
`

func (q *Queries) GetTrip(ctx context.Context, id int64) (Trip, error) {
	row := q.db.QueryRow(ctx, getTrip, id)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.Origin,
		&i.Destination,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.ActualStart,
		&i.ActualEnd,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTripForDriver = `-- name: GetTripForDriver :one
SELECT t.id, t.origin, t.destination, t.scheduled_start, t.scheduled_end,
       t.actual_start, t.actual_end, t.status, t.notes, t.created_at, t.updated_at
FROM trips t
JOIN assignments a ON a.trip_id = t.id
WHERE t.id = $1 AND a.driver_id = $2
`

type GetTripForDriverParams struct {
	TripID   int64
	DriverID int64
}

// Ownership in the WHERE clause: a trip id that is not the caller's returns no row.
func (q *Queries) GetTripForDriver(ctx context.Context, arg GetTripForDriverParams) (Trip, error) {
	row := q.db.QueryRow(ctx, getTripForDriver, arg.TripID, arg.DriverID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.Origin,
		&i.Destination,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.ActualStart,
		&i.ActualEnd,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTripsForDriver = `-- name: ListTripsForDriver :many
SELECT t.id, t.origin, t.destination, t.scheduled_start, t.scheduled_end,
       t.actual_start, t.actual_end, t.status, t.notes, t.created_at, t.updated_at,
       b.plate AS bus_plate
FROM trips t
JOIN assignments a ON a.trip_id = t.id
JOIN buses b ON b.id = a.bus_id
WHERE a.driver_id = $1
  AND t.status <> 'cancelled'
  AND t.scheduled_end >= $2
ORDER BY t.scheduled_start
`

type ListTripsForDriverParams struct {
	DriverID int64
	Since    time.Time
}

type ListTripsForDriverRow struct {
	ID             int64
	Origin         string
	Destination    string
	ScheduledStart time.Time
	ScheduledEnd   time.Time
	ActualStart    *time.Time
	ActualEnd      *time.Time
	Status         TripStatus
	Notes          *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	BusPlate       string
}

// A driver's own trips. Ownership lives in the WHERE clause: the driver id comes from
// the session, never from the request, and no query returns another driver's trips.
func (q *Queries) ListTripsForDriver(ctx context.Context, arg ListTripsForDriverParams) ([]ListTripsForDriverRow, error) {
	rows, err := q.db.Query(ctx, listTripsForDriver, arg.DriverID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTripsForDriverRow{}
	for rows.Next() {
		var i ListTripsForDriverRow
		if err := rows.Scan(
			&i.ID,
			&i.Origin,
			&i.Destination,
			&i.ScheduledStart,
			&i.ScheduledEnd,
			&i.ActualStart,
			&i.ActualEnd,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BusPlate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripsInRange = `-- name: ListTripsInRange :many
SELECT id, origin, destination, scheduled_start, scheduled_end, actual_start, actual_end,
       status, notes, created_at, updated_at
FROM trips
WHERE tstzrange(scheduled_start, scheduled_end, '[)') && tstzrange($1, $2, '[)')
ORDER BY scheduled_start, id
`

type ListTripsInRangeParams struct {
	RangeStart interface{}
	RangeEnd   interface{}
}

// Planning list and (step 4) the timeline: trips whose window touches [$1, $2).
func (q *Queries) ListTripsInRange(ctx context.Context, arg ListTripsInRangeParams) ([]Trip, error) {
	rows, err := q.db.Query(ctx, listTripsInRange, arg.RangeStart, arg.RangeEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trip{}
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.Origin,
			&i.Destination,
			&i.ScheduledStart,
			&i.ScheduledEnd,
			&i.ActualStart,
			&i.ActualEnd,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTripStatus = `-- name: SetTripStatus :one
UPDATE trips
SET status = $2
WHERE id = $1
RETURNING id, origin, destination, scheduled_start, scheduled_end, actual_start, actual_end,
          status, notes, created_at, updated_at
`

type SetTripStatusParams struct {
	ID     int64
	Status TripStatus
}

func (q *Queries) SetTripStatus(ctx context.Context, arg SetTripStatusParams) (Trip, error) {
	row := q.db.QueryRow(ctx, setTripStatus, arg.ID, arg.Status)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.Origin,
		&i.Destination,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.ActualStart,
		&i.ActualEnd,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const startTripAsDriver = `-- name: StartTripAsDriver :one
UPDATE trips
SET status = 'in_progress', actual_start = now()
FROM assignments a
WHERE trips.id = $1
  AND a.trip_id = trips.id
  AND a.driver_id = $2
  AND trips.status = 'planned'
RETURNING trips.id, trips.origin, trips.destination, trips.scheduled_start, trips.scheduled_end,
          trips.actual_start, trips.actual_end, trips.status, trips.notes,
          trips.created_at, trips.updated_at
`

type StartTripAsDriverParams struct {
	TripID   int64
	DriverID int64
}

// payroll-seam: actual_start is the worked-time clock payroll will sum.
// The driver id is matched in SQL, so a forged trip id cannot touch another driver's
// trip: a mismatch returns no row, which the service maps to "not found".
func (q *Queries) StartTripAsDriver(ctx context.Context, arg StartTripAsDriverParams) (Trip, error) {
	row := q.db.QueryRow(ctx, startTripAsDriver, arg.TripID, arg.DriverID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.Origin,
		&i.Destination,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.ActualStart,
		&i.ActualEnd,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTrip = `-- name: UpdateTrip :one
UPDATE trips
SET origin = $2, destination = $3, scheduled_start = $4, scheduled_end = $5, notes = $6
WHERE id = $1
RETURNING id, origin, destination, scheduled_start, scheduled_end, actual_start, actual_end,
          status, notes, created_at, updated_at
`

type UpdateTripParams struct {
	ID             int64
	Origin         string
	Destination    string
	ScheduledStart time.Time
	ScheduledEnd   time.Time
	Notes          *string
}

// Rescheduling an assigned trip cascades the new window onto its assignment, where the
// EXCLUDE constraints re-check it — so moving a trip into a clash fails here.
func (q *Queries) UpdateTrip(ctx context.Context, arg UpdateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, updateTrip,
		arg.ID,
		arg.Origin,
		arg.Destination,
		arg.ScheduledStart,
		arg.ScheduledEnd,
		arg.Notes,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.Origin,
		&i.Destination,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.ActualStart,
		&i.ActualEnd,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
