// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: trip_series.sql

package sqlcgen

import (
	"context"
	"time"
)

const createTripSeries = `-- name: CreateTripSeries :one
INSERT INTO trip_series (origin, destination, days_of_week, first_start, first_end, ends_on, payment_status, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, origin, destination, days_of_week, first_start, first_end, ends_on, payment_status, notes,
          created_at, updated_at
`

type CreateTripSeriesParams struct {
	Origin        string
	Destination   string
	DaysOfWeek    []int32
	FirstStart    time.Time
	FirstEnd      time.Time
	EndsOn        time.Time
	PaymentStatus PaymentStatus
	Notes         *string
}

func (q *Queries) CreateTripSeries(ctx context.Context, arg CreateTripSeriesParams) (TripSeries, error) {
	row := q.db.QueryRow(ctx, createTripSeries,
		arg.Origin,
		arg.Destination,
		arg.DaysOfWeek,
		arg.FirstStart,
		arg.FirstEnd,
		arg.EndsOn,
		arg.PaymentStatus,
		arg.Notes,
	)
	var i TripSeries
	err := row.Scan(
		&i.ID,
		&i.Origin,
		&i.Destination,
		&i.DaysOfWeek,
		&i.FirstStart,
		&i.FirstEnd,
		&i.EndsOn,
		&i.PaymentStatus,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
