// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package sqlcgen

import (
	"context"
	"time"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, role, driver_id, locale)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, password_hash, role, driver_id, locale, is_active, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Role         UserRole
	DriverID     *int64
	Locale       *string
}

// Used by the create-admin bootstrap command and, from step 3, by admin user
// management. driver_id must be non-null exactly when role = 'driver' (DB-enforced).
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.DriverID,
		arg.Locale,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.DriverID,
		&i.Locale,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, driver_id, locale, is_active, created_at, updated_at
FROM users
WHERE email = $1
`

// Login lookup. The handler always runs an argon2id verification afterwards, even when
// no row comes back, so response time does not reveal whether the email exists.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.DriverID,
		&i.Locale,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, driver_id, locale, is_active, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.DriverID,
		&i.Locale,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.email, u.password_hash, u.role, u.driver_id, u.locale, u.is_active,
       u.created_at, u.updated_at, d.full_name AS driver_name
FROM users u
LEFT JOIN drivers d ON d.id = u.driver_id
ORDER BY u.email
`

type ListUsersRow struct {
	ID           int64
	Email        string
	PasswordHash string
	Role         UserRole
	DriverID     *int64
	Locale       *string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DriverName   *string
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.DriverID,
			&i.Locale,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DriverName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserActive = `-- name: SetUserActive :one
UPDATE users SET is_active = $2
WHERE id = $1
RETURNING id, email, password_hash, role, driver_id, locale, is_active, created_at, updated_at
`

type SetUserActiveParams struct {
	ID       int64
	IsActive bool
}

// Users are deactivated, never deleted: audit_log.actor_user_id references them.
// The service deletes their sessions in the same transaction.
func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserActive, arg.ID, arg.IsActive)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.DriverID,
		&i.Locale,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserLocale = `-- name: SetUserLocale :exec
UPDATE users SET locale = $2 WHERE id = $1
`

type SetUserLocaleParams struct {
	ID     int64
	Locale *string
}

func (q *Queries) SetUserLocale(ctx context.Context, arg SetUserLocaleParams) error {
	_, err := q.db.Exec(ctx, setUserLocale, arg.ID, arg.Locale)
	return err
}

const setUserPassword = `-- name: SetUserPassword :one
UPDATE users SET password_hash = $2
WHERE id = $1
RETURNING id, email, password_hash, role, driver_id, locale, is_active, created_at, updated_at
`

type SetUserPasswordParams struct {
	ID           int64
	PasswordHash string
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.DriverID,
		&i.Locale,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
